image:
  repository: docker.pkg.github.com/mittwald/harbor-operator/harbor-operator
  # if no tag is given, the chart's appVersion is used
  # tag: latest
  pullPolicy: Always
  pullSecret: {}

env:
  helmClientRepositoryCachePath: /tmp/.helmcache
  helmClientRepositoryConfigPath: /tmp/.helmrepo

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: {}

fullnameOverride: {}

serviceAccount:
  name: {}
  create: {}