{{- $this := . }}
{{- range $instance := .Values.instances }}
  {{- range $registry := .registries }}
apiVersion: registries.mittwald.de/v1alpha1
kind: Registry
metadata:
  name: {{ $registry.name }}
  labels:
    {{- include "chart.labels" $this | nindent 4 }}
spec:
  parentInstance:
    name: {{ $instance.name }}
  name: {{ $registry.name }}
  type: {{ $registry.type }}
  url: {{ $registry.url }}

  {{- if $registry.id }}
  id: {{ $registry.id }}
  {{- end }}

  {{- if $registry.description }}
  description: {{ $registry.description }}
  {{- end }}

  {{- if $registry.token_service_url }}
  token_service_url: {{ $registry.token_service_url }}
  {{- end }}

  {{- if $registry.credential }}
  credential:
    {{- with $registry.credential }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

  {{- if $registry.insecure }}
  insecure: {{ $registry.insecure }}
  {{- end }}
---
  {{- end }}
{{- end }}